### ISSUE TITLE
req: provide deb repository

### ISSUE THREAD

**Issue by tokred** [smallstep/cli#660]
### What would you like to be added
It would be amazing if the releases of both `step-cli` and `step-ca` would be published in a Debian/Ubuntu repository. Not in the "official" Debian/Ubuntu repos but in a separate "Smallstep repo" which could be added in one's `sources.list`.

Many OSS projects do this for good reasons, and considering .deb files are already created as part of Smallstep's build process, covering this would require only minimal effort (i.e. automatically signing the .deb's, generating the meta data and putting into the right folder structure). Traffic does not seem a concern, considering the existing release downloads are self-hosted on `dl.step.sm` already.

### Why this is needed
Operationality: This would allow to use standard APT package managers, especially **_package manager-facilitated installs and updates!_**

The current release model with publishing .deb files as releases on GitHub is understandable but completely negates well-established, package manager-based software handling and maintenance. It is quite hard to distribute and maintain software updates with those "static" .deb's to multiple machines (and requires manual checking if updates are available!), compared to being able to simply add a "Smallstep repo" to `sources.list` and letting APT do its magic via `apt upgrade` (or even `unattended-upgrades`).

Maybe a service like [Cloudsmith](https://cloudsmith.com/) could be used? No affiliation, just saw it being used by e.g. ISC

Regards

**Comment by sylr** [comment]
`step-ssh` as well.

**Comment by nickbouwhuis** [comment]
I second this. Would make deployment a lot easier, as well as the update process. 

Hosting a repository should not be too much work. There is already a process in place for building `deb` files.

You could use open-source software like Nexus Repo Manager to host an apt/dnf repository.

**Comment by hax0rbana-adam** [comment]
Seeing as how this has been open since March and hasn't even been triaged yet, I don't have any hope of the maintainers taking this on, so I decided to add this to my own personal repo. If others want to use it, go for it.

# Challenges
Challenges with SmallStep's current release process include:
- No directory listings on the URLs listed in the [Debian installation instructions](https://smallstep.com/docs/step-ca/installation/#debian)
- No indication what version of `step-ssh` is being installed in the [installation instructions](https://smallstep.com/docs/ssh/hosts-step-by-step)
- There doesn't appear to be a github repo for step-ssh
- There's no ARM releases for `step-cli` (sorry @spyesx and others who use ARM computers)
- The latest version of `step-ca` and `step-cli` is 0.23.0, but the latest `step-ssh` release is only 0.21.0-1

These challenges are trivial to overcome manually, but rather annoying to overcome when trying to automate this. I hope they step up their automation game and fix these things in the future.

# Sources
Because there's not GitHub repos for all the projects we want, and there are so many repos for things that do not belong in an apt repo, it's only proper to document where the things in my repo came from.

- https://github.com/smallstep/cli/releases/
- https://github.com/smallstep/certificates/releases/
- https://dl.step.sm/s3/ssh/docs-ssh-host-step-by-step/step-ssh_latest_amd64.deb
  - Downloaded, installed, and then renamed to `step-ssh_0.21.0-1_amd64.deb`

# Adding my repo
There are a number of ways to add a 3rd party repo, but here's one that should be compatible with both old and new Debian systems.

```sh
echo 'deb https://repo.hax0rbana.org/debs /' > /etc/apt/sources.list.d/hax0rbana.list
wget -qO - https://repo.hax0rbana.org/debs/KEY.gpg | apt-key add -
apt update
apt install -y step-ca step-cli step-ssh
```

Or, if you use Ansible, below is a playbook that will add the repo, install `step-cli` and `step-ssh` everywhere, and install `step-ca` if the host is in a group called `ca`.

```yaml
# Installs step-cli and step-ssh from a third party repo
#       
- hosts: all
  remote_user: root
  tasks:
    - name: Add the signing key for the apt repo
      ansible.builtin.apt_key:
        url: https://repo.hax0rbana.org/debs/KEY.gpg
    - name: Add repository into sources list
      ansible.builtin.apt_repository:
        repo: deb https://repo.hax0rbana.org/debs /
    - name: Installing step-cli and step-ssh
      ansible.builtin.package:
        update_cache: true
        name:
          - step-cli
          - step-ssh
    - name: Installing step-ca
      ansible.builtin.package:
        name: step-ca
      when: "'ca' in group_names"
```
